[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "ses"
version = "0.0.1"
dynamic = ["dependencies"]

[tools.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}